name: baseEnv
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - certifi=2016.2.28=py36_0
  - openssl=1.0.2l=0
  - python=3.6.2=0
  - readline=6.2=2
  - setuptools=36.4.0=py36_1
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py36_0
  - xz=5.2.3=0
  - zlib=1.2.11=0
  - pip:
    - astroid==2.8.3
    - backports-entry-points-selectable==1.1.0
    - cfgv==3.3.1
    - distlib==0.3.3
    - filelock==3.3.1
    - identify==2.3.0
    - importlib-metadata==4.8.1
    - importlib-resources==5.3.0
    - isort==5.9.3
    - lazy-object-proxy==1.6.0
    - mccabe==0.6.1
    - nodeenv==1.6.0
    - pip==21.3
    - platformdirs==2.4.0
    - pre-commit==2.15.0
    - pylint==2.11.1
    - pyyaml==6.0
    - six==1.16.0
    - toml==0.10.2
    - typed-ast==1.4.3
    - typing-extensions==3.10.0.2
    - virtualenv==20.8.1
    - wrapt==1.13.2
    - yapf==0.31.0
    - zipp==3.6.0
